# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.consumer_api import ConsumerApi


class TestConsumerApi(unittest.TestCase):
    """ConsumerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsumerApi()

    def tearDown(self) -> None:
        pass

    def test_api_consumer_get(self) -> None:
        """Test case for api_consumer_get

        """
        pass

    def test_api_consumer_post(self) -> None:
        """Test case for api_consumer_post

        """
        pass

    def test_api_consumer_username_delete(self) -> None:
        """Test case for api_consumer_username_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
