# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.request_status import RequestStatus

class TestRequestStatus(unittest.TestCase):
    """RequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestStatus(self):
        """Test RequestStatus"""
        # inst = RequestStatus()

if __name__ == '__main__':
    unittest.main()
