# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.create_key_request import CreateKeyRequest

class TestCreateKeyRequest(unittest.TestCase):
    """CreateKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateKeyRequest:
        """Test CreateKeyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateKeyRequest`
        """
        model = CreateKeyRequest()
        if include_optional:
            return CreateKeyRequest(
                owner = '',
                validity_days = 56
            )
        else:
            return CreateKeyRequest(
        )
        """

    def testCreateKeyRequest(self):
        """Test CreateKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
