# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.audit_logs_api import AuditLogsApi


class TestAuditLogsApi(unittest.TestCase):
    """AuditLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditLogsApi()

    def tearDown(self) -> None:
        pass

    def test_api_audit_logs_export_get(self) -> None:
        """Test case for api_audit_logs_export_get

        """
        pass

    def test_api_audit_logs_get(self) -> None:
        """Test case for api_audit_logs_get

        """
        pass

    def test_api_audit_logs_stats_get(self) -> None:
        """Test case for api_audit_logs_stats_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
