# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.access_request_api import AccessRequestApi


class TestAccessRequestApi(unittest.TestCase):
    """AccessRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessRequestApi()

    def tearDown(self) -> None:
        pass

    def test_api_access_request_get(self) -> None:
        """Test case for api_access_request_get

        """
        pass

    def test_api_access_request_id_approve_post(self) -> None:
        """Test case for api_access_request_id_approve_post

        """
        pass

    def test_api_access_request_id_reject_post(self) -> None:
        """Test case for api_access_request_id_reject_post

        """
        pass

    def test_api_access_request_submit_post(self) -> None:
        """Test case for api_access_request_submit_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
