# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.audit_log_entry import AuditLogEntry

class TestAuditLogEntry(unittest.TestCase):
    """AuditLogEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLogEntry:
        """Test AuditLogEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLogEntry`
        """
        model = AuditLogEntry()
        if include_optional:
            return AuditLogEntry(
                id = 56,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user = '',
                action = '',
                resource = '',
                status_code = 56,
                details = None,
                details_json = '',
                correlation_id = '',
                operator_ip = '',
                request_id = ''
            )
        else:
            return AuditLogEntry(
        )
        """

    def testAuditLogEntry(self):
        """Test AuditLogEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
