# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.alert_rule import AlertRule

class TestAlertRule(unittest.TestCase):
    """AlertRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertRule:
        """Test AlertRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertRule`
        """
        model = AlertRule()
        if include_optional:
            return AlertRule(
                id = '',
                name = '0',
                metric_name = '0',
                threshold = 1.337,
                duration = '',
                is_enabled = True,
                notification_channels = [
                    ''
                    ],
                severity = ''
            )
        else:
            return AlertRule(
                name = '0',
                metric_name = '0',
        )
        """

    def testAlertRule(self):
        """Test AlertRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
