# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.api_service_metadata import ApiServiceMetadata

class TestApiServiceMetadata(unittest.TestCase):
    """ApiServiceMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiServiceMetadata:
        """Test ApiServiceMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiServiceMetadata`
        """
        model = ApiServiceMetadata()
        if include_optional:
            return ApiServiceMetadata(
                id = 56,
                name = '0',
                description = '',
                base_path = '0',
                open_api_url = '0',
                owner_team = '',
                is_public = True,
                last_synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiServiceMetadata(
                name = '0',
                base_path = '0',
                open_api_url = '0',
        )
        """

    def testApiServiceMetadata(self):
        """Test ApiServiceMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
