# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.mock_api import MockApi


class TestMockApi(unittest.TestCase):
    """MockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MockApi()

    def tearDown(self) -> None:
        pass

    def test_api_mock_get(self) -> None:
        """Test case for api_mock_get

        """
        pass

    def test_api_mock_id_delete(self) -> None:
        """Test case for api_mock_id_delete

        """
        pass

    def test_api_mock_id_put(self) -> None:
        """Test case for api_mock_id_put

        """
        pass

    def test_api_mock_post(self) -> None:
        """Test case for api_mock_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
