# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.alert_rules_api import AlertRulesApi


class TestAlertRulesApi(unittest.TestCase):
    """AlertRulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlertRulesApi()

    def tearDown(self) -> None:
        pass

    def test_api_alert_rules_get(self) -> None:
        """Test case for api_alert_rules_get

        """
        pass

    def test_api_alert_rules_id_delete(self) -> None:
        """Test case for api_alert_rules_id_delete

        """
        pass

    def test_api_alert_rules_id_toggle_put(self) -> None:
        """Test case for api_alert_rules_id_toggle_put

        """
        pass

    def test_api_alert_rules_post(self) -> None:
        """Test case for api_alert_rules_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
