# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.access_request import AccessRequest

class TestAccessRequest(unittest.TestCase):
    """AccessRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessRequest:
        """Test AccessRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessRequest`
        """
        model = AccessRequest()
        if include_optional:
            return AccessRequest(
                id = 56,
                project_name = '0',
                applicant_email = '0',
                requested_tier = '0',
                purpose = '0',
                status = 0,
                admin_comment = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                processed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AccessRequest(
                project_name = '0',
                applicant_email = '0',
                requested_tier = '0',
                purpose = '0',
        )
        """

    def testAccessRequest(self):
        """Test AccessRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
