# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.whitelist_entry import WhitelistEntry

class TestWhitelistEntry(unittest.TestCase):
    """WhitelistEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhitelistEntry:
        """Test WhitelistEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhitelistEntry`
        """
        model = WhitelistEntry()
        if include_optional:
            return WhitelistEntry(
                id = '',
                route_id = '0',
                ip_cidr = '0',
                reason = '',
                added_by = '',
                added_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WhitelistEntry(
                route_id = '0',
                ip_cidr = '0',
        )
        """

    def testWhitelistEntry(self):
        """Test WhitelistEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
