# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.blacklist_api import BlacklistApi


class TestBlacklistApi(unittest.TestCase):
    """BlacklistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlacklistApi()

    def tearDown(self) -> None:
        pass

    def test_api_blacklist_get(self) -> None:
        """Test case for api_blacklist_get

        Retrieves the current IP blacklist.
        """
        pass

    def test_api_blacklist_post(self) -> None:
        """Test case for api_blacklist_post

        Adds or removes an IP/CIDR to/from the blacklist.
        """
        pass


if __name__ == '__main__':
    unittest.main()
