# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.load_test_api import LoadTestApi


class TestLoadTestApi(unittest.TestCase):
    """LoadTestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoadTestApi()

    def tearDown(self) -> None:
        pass

    def test_api_load_test_run_post(self) -> None:
        """Test case for api_load_test_run_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
