# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.sync_status_api import SyncStatusApi


class TestSyncStatusApi(unittest.TestCase):
    """SyncStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SyncStatusApi()

    def tearDown(self) -> None:
        pass

    def test_api_sync_status_get(self) -> None:
        """Test case for api_sync_status_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
