# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.whitelist_api import WhitelistApi


class TestWhitelistApi(unittest.TestCase):
    """WhitelistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WhitelistApi()

    def tearDown(self) -> None:
        pass

    def test_api_whitelist_route_route_id_get(self) -> None:
        """Test case for api_whitelist_route_route_id_get

        Retrieves the IP whitelist for a specific route.
        """
        pass

    def test_api_whitelist_route_route_id_post(self) -> None:
        """Test case for api_whitelist_route_route_id_post

        Adds or removes an IP/CIDR to/from a route's whitelist.
        """
        pass


if __name__ == '__main__':
    unittest.main()
