# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.api_test_scenario import ApiTestScenario

class TestApiTestScenario(unittest.TestCase):
    """ApiTestScenario unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTestScenario:
        """Test ApiTestScenario
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTestScenario`
        """
        model = ApiTestScenario()
        if include_optional:
            return ApiTestScenario(
                id = 56,
                service_id = 56,
                name = '0',
                endpoint = '0',
                http_method = '',
                expected_status_code = 56,
                last_result = '',
                last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ApiTestScenario(
                service_id = 56,
                name = '0',
                endpoint = '0',
        )
        """

    def testApiTestScenario(self):
        """Test ApiTestScenario"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
