# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.test_execution_api import TestExecutionApi


class TestTestExecutionApi(unittest.TestCase):
    """TestExecutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestExecutionApi()

    def tearDown(self) -> None:
        pass

    def test_api_test_execution_run_id_post(self) -> None:
        """Test case for api_test_execution_run_id_post

        """
        pass

    def test_api_test_execution_scenarios_post(self) -> None:
        """Test case for api_test_execution_scenarios_post

        """
        pass

    def test_api_test_execution_scenarios_service_id_get(self) -> None:
        """Test case for api_test_execution_scenarios_service_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
