# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_api_analytics_errors_get(self) -> None:
        """Test case for api_analytics_errors_get

        """
        pass

    def test_api_analytics_latency_get(self) -> None:
        """Test case for api_analytics_latency_get

        """
        pass

    def test_api_analytics_requests_get(self) -> None:
        """Test case for api_analytics_requests_get

        """
        pass

    def test_api_analytics_sla_get(self) -> None:
        """Test case for api_analytics_sla_get

        """
        pass

    def test_api_analytics_top_slow_routes_get(self) -> None:
        """Test case for api_analytics_top_slow_routes_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
