# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.blacklist_entry import BlacklistEntry

class TestBlacklistEntry(unittest.TestCase):
    """BlacklistEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlacklistEntry:
        """Test BlacklistEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlacklistEntry`
        """
        model = BlacklistEntry()
        if include_optional:
            return BlacklistEntry(
                id = '',
                ip_or_cidr = '0',
                reason = '',
                added_by = '',
                added_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BlacklistEntry(
                ip_or_cidr = '0',
        )
        """

    def testBlacklistEntry(self):
        """Test BlacklistEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
