# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.models.pii_masking_rule import PiiMaskingRule

class TestPiiMaskingRule(unittest.TestCase):
    """PiiMaskingRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PiiMaskingRule:
        """Test PiiMaskingRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PiiMaskingRule`
        """
        model = PiiMaskingRule()
        if include_optional:
            return PiiMaskingRule(
                id = 56,
                route_id = '0',
                field_path = '0',
                regex_pattern = '0',
                replace_pattern = '0',
                is_active = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = ''
            )
        else:
            return PiiMaskingRule(
                route_id = '0',
                field_path = '0',
                regex_pattern = '0',
                replace_pattern = '0',
        )
        """

    def testPiiMaskingRule(self):
        """Test PiiMaskingRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
