# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.api_catalog_api import ApiCatalogApi


class TestApiCatalogApi(unittest.TestCase):
    """ApiCatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiCatalogApi()

    def tearDown(self) -> None:
        pass

    def test_api_api_catalog_get(self) -> None:
        """Test case for api_api_catalog_get

        """
        pass

    def test_api_api_catalog_register_post(self) -> None:
        """Test case for api_api_catalog_register_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
