# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.pii_masking_api import PiiMaskingApi


class TestPiiMaskingApi(unittest.TestCase):
    """PiiMaskingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PiiMaskingApi()

    def tearDown(self) -> None:
        pass

    def test_api_pii_masking_get(self) -> None:
        """Test case for api_pii_masking_get

        Retrieves all PII masking rules.
        """
        pass

    def test_api_pii_masking_id_delete(self) -> None:
        """Test case for api_pii_masking_id_delete

        Deletes a PII masking rule from the system and APISIX.
        """
        pass

    def test_api_pii_masking_id_put(self) -> None:
        """Test case for api_pii_masking_id_put

        Updates an existing PII masking rule.
        """
        pass

    def test_api_pii_masking_post(self) -> None:
        """Test case for api_pii_masking_post

        Creates a new PII masking rule governing APISIX traffic.
        """
        pass


if __name__ == '__main__':
    unittest.main()
