# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from milk_api_client.api.keys_api import KeysApi


class TestKeysApi(unittest.TestCase):
    """KeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeysApi()

    def tearDown(self) -> None:
        pass

    def test_api_keys_consumer_name_rotate_post(self) -> None:
        """Test case for api_keys_consumer_name_rotate_post

        """
        pass

    def test_api_keys_post(self) -> None:
        """Test case for api_keys_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
