# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from milk_api_client.models.request_status import RequestStatus
from typing import Optional, Set
from typing_extensions import Self

class AccessRequest(BaseModel):
    """
    AccessRequest
    """ # noqa: E501
    id: Optional[StrictInt] = None
    project_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="projectName")
    applicant_email: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="applicantEmail")
    requested_tier: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="requestedTier")
    purpose: Annotated[str, Field(min_length=1, strict=True)]
    status: Optional[RequestStatus] = None
    admin_comment: Optional[StrictStr] = Field(default=None, alias="adminComment")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    processed_at: Optional[datetime] = Field(default=None, alias="processedAt")
    __properties: ClassVar[List[str]] = ["id", "projectName", "applicantEmail", "requestedTier", "purpose", "status", "adminComment", "createdAt", "processedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if admin_comment (nullable) is None
        # and model_fields_set contains the field
        if self.admin_comment is None and "admin_comment" in self.model_fields_set:
            _dict['adminComment'] = None

        # set to None if processed_at (nullable) is None
        # and model_fields_set contains the field
        if self.processed_at is None and "processed_at" in self.model_fields_set:
            _dict['processedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "projectName": obj.get("projectName"),
            "applicantEmail": obj.get("applicantEmail"),
            "requestedTier": obj.get("requestedTier"),
            "purpose": obj.get("purpose"),
            "status": obj.get("status"),
            "adminComment": obj.get("adminComment"),
            "createdAt": obj.get("createdAt"),
            "processedAt": obj.get("processedAt")
        })
        return _obj


