# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ApiTestScenario(BaseModel):
    """
    ApiTestScenario
    """ # noqa: E501
    id: Optional[StrictInt] = None
    service_id: StrictInt = Field(alias="serviceId")
    name: Annotated[str, Field(min_length=1, strict=True)]
    endpoint: Annotated[str, Field(min_length=1, strict=True)]
    http_method: Optional[StrictStr] = Field(default=None, alias="httpMethod")
    expected_status_code: Optional[StrictInt] = Field(default=None, alias="expectedStatusCode")
    last_result: Optional[StrictStr] = Field(default=None, alias="lastResult")
    last_run_at: Optional[datetime] = Field(default=None, alias="lastRunAt")
    __properties: ClassVar[List[str]] = ["id", "serviceId", "name", "endpoint", "httpMethod", "expectedStatusCode", "lastResult", "lastRunAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiTestScenario from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if http_method (nullable) is None
        # and model_fields_set contains the field
        if self.http_method is None and "http_method" in self.model_fields_set:
            _dict['httpMethod'] = None

        # set to None if last_result (nullable) is None
        # and model_fields_set contains the field
        if self.last_result is None and "last_result" in self.model_fields_set:
            _dict['lastResult'] = None

        # set to None if last_run_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_run_at is None and "last_run_at" in self.model_fields_set:
            _dict['lastRunAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiTestScenario from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "serviceId": obj.get("serviceId"),
            "name": obj.get("name"),
            "endpoint": obj.get("endpoint"),
            "httpMethod": obj.get("httpMethod"),
            "expectedStatusCode": obj.get("expectedStatusCode"),
            "lastResult": obj.get("lastResult"),
            "lastRunAt": obj.get("lastRunAt")
        })
        return _obj


