# coding: utf-8

"""
    MilkApiManager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AuditLogEntry(BaseModel):
    """
    AuditLogEntry
    """ # noqa: E501
    id: Optional[StrictInt] = None
    timestamp: Optional[datetime] = None
    user: Optional[StrictStr] = None
    action: Optional[StrictStr] = None
    resource: Optional[StrictStr] = None
    status_code: Optional[StrictInt] = Field(default=None, alias="statusCode")
    details: Optional[Any] = None
    details_json: Optional[StrictStr] = Field(default=None, alias="detailsJson")
    correlation_id: Optional[StrictStr] = Field(default=None, alias="correlationId")
    operator_ip: Optional[StrictStr] = Field(default=None, alias="operatorIp")
    request_id: Optional[StrictStr] = Field(default=None, alias="requestId")
    __properties: ClassVar[List[str]] = ["id", "timestamp", "user", "action", "resource", "statusCode", "details", "detailsJson", "correlationId", "operatorIp", "requestId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuditLogEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if action (nullable) is None
        # and model_fields_set contains the field
        if self.action is None and "action" in self.model_fields_set:
            _dict['action'] = None

        # set to None if resource (nullable) is None
        # and model_fields_set contains the field
        if self.resource is None and "resource" in self.model_fields_set:
            _dict['resource'] = None

        # set to None if details (nullable) is None
        # and model_fields_set contains the field
        if self.details is None and "details" in self.model_fields_set:
            _dict['details'] = None

        # set to None if details_json (nullable) is None
        # and model_fields_set contains the field
        if self.details_json is None and "details_json" in self.model_fields_set:
            _dict['detailsJson'] = None

        # set to None if correlation_id (nullable) is None
        # and model_fields_set contains the field
        if self.correlation_id is None and "correlation_id" in self.model_fields_set:
            _dict['correlationId'] = None

        # set to None if operator_ip (nullable) is None
        # and model_fields_set contains the field
        if self.operator_ip is None and "operator_ip" in self.model_fields_set:
            _dict['operatorIp'] = None

        # set to None if request_id (nullable) is None
        # and model_fields_set contains the field
        if self.request_id is None and "request_id" in self.model_fields_set:
            _dict['requestId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuditLogEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "timestamp": obj.get("timestamp"),
            "user": obj.get("user"),
            "action": obj.get("action"),
            "resource": obj.get("resource"),
            "statusCode": obj.get("statusCode"),
            "details": obj.get("details"),
            "detailsJson": obj.get("detailsJson"),
            "correlationId": obj.get("correlationId"),
            "operatorIp": obj.get("operatorIp"),
            "requestId": obj.get("requestId")
        })
        return _obj


