global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using System.Net.Http;
global using Microsoft.Extensions.DependencyInjection;
global using System.Net.Http.Json;
