#!/bin/bash
# Unified Verification Script (Linux/WSL)
# This script is the "Source of Truth" for development stability.

set -e
REPORT_FILE="E2E_TEST_REPORT.md"
START_TIME=$(date +%s)

echo "==========================================================="
echo "   MILK API MANAGER - FULL SYSTEM VERIFICATION"
echo "==========================================================="

# Determine test mode
IS_TEST_MODE="${USE_TEST_MODE:-false}"

if [ "$IS_TEST_MODE" = "true" ]; then
    echo "[Mode] Running in TEST MODE (MockApisixClient, no APISIX required)"
else
    echo "[Mode] Running in FULL MODE (real APISIX required)"
fi

# 1. Infrastructure Check
echo -e "\n[Step 1/3] Checking Infrastructure (Docker)..."

if [ "$IS_TEST_MODE" = "true" ]; then
    # Test Mode: only check essential containers
    REQUIRED_CONTAINERS=("milk-db" "milk-backend" "milk-worker")
else
    # Full Mode: check all core containers
    REQUIRED_CONTAINERS=("apisix" "etcd" "prometheus" "grafana")
fi

MISSING=()
for container in "${REQUIRED_CONTAINERS[@]}"; do
    if ! docker ps --format '{{.Names}}' | grep -q "$container"; then
        MISSING+=("$container")
    fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
    echo "   ⚠️Missing: ${MISSING[*]}"
else
    echo "   ✅All core infrastructure containers are running."
fi

# Wait for key services to be READY (Crucial for CI stability)
echo -e "\n[Wait] Verifying Service Connectivity..."

if [ "$IS_TEST_MODE" = "true" ]; then
    # Test Mode: wait for milk-backend and milk-admin-ui health
    echo "   Waiting for milk-backend (5001)..."
    for i in {1..30}; do
        if curl -sf http://localhost:5001/health/live > /dev/null 2>&1; then
            echo "   [PASS] milk-backend is READY."
            break
        fi
        [ $i -eq 30 ] && echo "   [WARN] milk-backend wait timed out."
        sleep 2
    done

    echo "   Waiting for milk-admin-ui (5000)..."
    for i in {1..30}; do
        if curl -sf http://localhost:5000/health > /dev/null 2>&1; then
            echo "   [PASS] milk-admin-ui is READY."
            break
        fi
        [ $i -eq 30 ] && echo "   [WARN] milk-admin-ui wait timed out."
        sleep 2
    done
else
    # Full Mode: wait for APISIX Admin API
    for i in {1..30}; do
        if curl -s http://localhost:9180/apisix/admin/routes -H "X-API-KEY: edd1c9f034335f136f87ad84b625c88b" > /dev/null; then
            echo "   [PASS] APISIX Gateway is READY."
            break
        fi
        [ $i -eq 30 ] && echo "   [WARN] APISIX wait timed out."
        sleep 2
    done
fi

# 2. .NET Unit Tests
echo -e "\n[Step 2/3] Running .NET Unit Tests..."
if dotnet test backend/ --logger "console;verbosity=normal"; then
    DOTNET_STATUS="✅OK"
    DOTNET_CODE=0
else
    DOTNET_STATUS="❌FAIL"
    DOTNET_CODE=1
fi

# 3. Playwright E2E Tests
echo -e "\n[Step 3/3] Running Playwright E2E Tests..."
cd e2e
# Ensure dependencies and browsers are present
if [ ! -d "node_modules" ]; then
    echo "   [Info] Installing E2E dependencies..."
    npm install --silent
fi

echo "   [Info] Installing Playwright browsers..."
npx playwright install chromium

export BASE_URL="http://localhost:5000"
if npm test; then
    E2E_STATUS="✅OK"
    E2E_CODE=0
else
    E2E_STATUS="❌FAIL"
    E2E_CODE=1
fi
cd ..

# Generate Consolidated Report
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
OVERALL_STATUS="FAILED ❌"
if [ $DOTNET_CODE -eq 0 ] && [ $E2E_CODE -eq 0 ]; then
    OVERALL_STATUS="PASSED ✅"
fi

TEST_MODE_LABEL=""
if [ "$IS_TEST_MODE" = "true" ]; then
    TEST_MODE_LABEL=" (Test Mode - MockApisixClient)"
fi

cat <<EOF > "$REPORT_FILE"
# System Verification Report ($(date '+%Y-%m-%d %H:%M:%S'))${TEST_MODE_LABEL}

## Summary
- **Duration:** ${DURATION} seconds
- **Overall Status:** $OVERALL_STATUS
- **Mode:** $([ "$IS_TEST_MODE" = "true" ] && echo "Test Mode (Mock)" || echo "Full Integration")

## Component Breakdown
| Component | Status | Details |
|-----------|--------|---------|
| .NET Backend | $DOTNET_STATUS | 78 Unit Tests |
| Admin UI | $E2E_STATUS | Playwright E2E |

---
*Generated by OpenClaw Development Flow*
EOF

# Output to GitHub Summary if available
if [ -n "$GITHUB_STEP_SUMMARY" ]; then
    cat "$REPORT_FILE" >> "$GITHUB_STEP_SUMMARY"
fi

echo -e "\nReport generated: $REPORT_FILE"
echo "==========================================================="

if [ $DOTNET_CODE -ne 0 ] || [ $E2E_CODE -ne 0 ]; then
    echo "❌ Verification FAILED!"
    exit 1
else
    echo "✅ Verification PASSED!"
    exit 0
fi
