# Unified Verification Script for Milk API Manager System
# This script is the "Source of Truth" for development stability.

$ErrorActionPreference = "Continue"
$ReportFile = "E2E_TEST_REPORT.md"
$StartTime = Get-Date

Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host "   MILK API MANAGER - FULL SYSTEM VERIFICATION" -ForegroundColor Cyan
Write-Host "===========================================================" -ForegroundColor Cyan

# 1. Infrastructure Check
Write-Host "`n[Step 1/4] Checking Infrastructure (Docker)..." -ForegroundColor Yellow
$containers = docker ps --format "{{.Names}}"
$required = @("apisix", "etcd", "prometheus", "grafana")
$missing = @()

foreach ($r in $required) {
    if (!($containers -match $r)) { $missing += $r }
}

if ($missing.Count -gt 0) {
    Write-Host "   [FAIL] Missing containers: $($missing -join ', ')" -ForegroundColor Red
    Write-Host "   Please run 'docker-compose up -d' first." -ForegroundColor Gray
} else {
    Write-Host "   [PASS] All core infrastructure containers are running." -ForegroundColor Green
}

# 2. .NET Unit & Integration Tests
Write-Host "`n[Step 2/4] Running .NET Unit Tests..." -ForegroundColor Yellow
$dotnetResult = dotnet test backend/MilkApiManager.Tests/MilkApiManager.Tests.csproj --logger "console;verbosity=normal"
$dotnetExitCode = $LASTEXITCODE

if ($dotnetExitCode -eq 0) {
    Write-Host "   [PASS] .NET Tests Passed!" -ForegroundColor Green
} else {
    Write-Host "   [FAIL] .NET Tests Failed!" -ForegroundColor Red
}

# 3. Python Smoke Tests (API Connectivity)
Write-Host "`n[Step 3/4] Running API Smoke Tests..." -ForegroundColor Yellow
$smokeResult = python test_complete.py
$smokeExitCode = $LASTEXITCODE

if ($smokeExitCode -eq 0) {
    Write-Host "   [PASS] API Smoke Tests Passed!" -ForegroundColor Green
} else {
    Write-Host "   [FAIL] API Smoke Tests Failed!" -ForegroundColor Red
}

# 4. Playwright E2E Tests (UI & Gateway)
Write-Host "`n[Step 4/4] Running Playwright E2E Tests..." -ForegroundColor Yellow
$env:BASE_URL = "http://127.0.0.1:5000"
Set-Location e2e
$e2eResult = npm test
$e2eExitCode = $LASTEXITCODE
Set-Location ..

if ($e2eExitCode -eq 0) {
    Write-Host "   [PASS] E2E Tests Passed!" -ForegroundColor Green
} else {
    Write-Host "   [FAIL] E2E Tests Failed!" -ForegroundColor Red
}

# Generate Consolidated Report
$EndTime = Get-Date
$Duration = $EndTime - $StartTime
$OverallStatus = "FAILED"
if ($dotnetExitCode -eq 0 -and $smokeExitCode -eq 0 -and $e2eExitCode -eq 0) {
    $OverallStatus = "PASSED"
}

$ReportContent = @"
# System Verification Report ($($EndTime.ToString("yyyy-MM-dd HH:mm:ss")))

## Summary
- **Start Time:** $($StartTime.ToString("HH:mm:ss"))
- **Duration:** $($Duration.TotalSeconds.ToString("F2")) seconds
- **Overall Status:** $OverallStatus

## Component Breakdown
| Component | Status | Details |
|-----------|--------|---------|
| .NET Backend | $(if ($dotnetExitCode -eq 0) { "OK" } else { "FAIL" }) | 48 Unit Tests |
| API Gateway | $(if ($smokeExitCode -eq 0) { "OK" } else { "FAIL" }) | Python Smoke Test |
| Admin UI | $(if ($e2eExitCode -eq 0) { "OK" } else { "FAIL" }) | Playwright E2E |

## Infrastructure
- **Docker Health:** $(if ($missing.Count -eq 0) { "Healthy" } else { "Unhealthy (Missing: $($missing -join ', '))" })

---
*Generated by OpenClaw Development Flow*
"@

$ReportContent | Out-File -FilePath $ReportFile -Encoding utf8
Write-Host "`nReport generated: $ReportFile" -ForegroundColor Cyan
Write-Host "===========================================================" -ForegroundColor Cyan
